=== BUTR/Bannerlord.ButterLib/resources/language.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xsd:element name="base">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="tags">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="tag">
								<xsd:complexType>
									<xsd:attribute name="language" type="xsd:string" use="required" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="strings">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" name="string">
								<xsd:complexType>
									<xsd:attribute name="id" type="xsd:string" use="required" />
									<xsd:attribute name="text" type="xsd:string" use="required" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
</xs:schema>

=== BUTR/Bannerlord.ButterLib/src/Bannerlord.ButterLib.Implementation/_Module/Languages/RU/std_module_strings_xml.xml
<?xml version="1.0" encoding="utf-8"?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="https://www.w3schools.com/xml ../../../../../resources/language.xsd" type="string">
  <tags>
    <tag language="Русский" />
  </tags>
  <strings>
    <string id="PZthBmJc9B" text="Не удалось загрузить Идентификатор Кампаний ButterLib! Смотрите детали в файле лога мода." />
    <string id="UdgidGXLwg" text="{BASE_DESCRIPTOR_HERO.NAME}{?BASE_DESCRIPTOR_HERO.CLAN} {BASE_DESCRIPTOR_HERO.CLAN_NAME}{?}{\?}{?BASE_DESCRIPTOR_HERO.BIRTHPLACE} из {BASE_DESCRIPTOR_HERO.BIRTHPLACE_NAME}{?}, место рождения неизвестно{\?}, {BASE_DESCRIPTOR_HERO.AGE}, {?BASE_DESCRIPTOR_HERO_PARENTS}{BASE_DESCRIPTOR_HERO_PARENTS.INFO}{?}родители неизвестны{\?}.{?BASE_DESCRIPTOR_HERO.CULTURE} {BASE_DESCRIPTOR_HERO.CULTURE_NAME}.{?}{\?}" />
    <string id="svZkgB1GgB" text="{?BASE_DESCRIPTOR_HERO.GENDER}дочь{?}сын{\?} {BASE_DESCRIPTOR_HERO.PARENTS_BEGIN}{?BASE_DESCRIPTOR_HERO.FULL_FAMILY} и {?}{\?}{BASE_DESCRIPTOR_HERO.PARENTS_END}" />
    <string id="gRz8MZ0YZ7" text="Этой игре не присвоен ID. Скорее всего она была начта до установки Идентификатора Кампаний ButterLib. Мы нашли другие текущие кампании, уже получившие идентификатор и имеющие схожие характеристики исходного персонажа. Если эта игра относится к одной из них, выберите соответствующую опцию." />
    <string id="zed49rdkQR" text="Выберите '{NEW_ID}', если загруженное сохранение - это отдельная кампания, которая не имеет ничего общего с предлагаемыми опциями. В этом случае ей будет присвоен новый идентификатор." />
    <string id="4BuIRaILsb" text="Выберите идентифицированную кампанию" />
    <string id="wF4qRrhmEu" text="Присвоить новый ID" />
    <string id="25Ts3iQnv6" text="Это отдельная кампания, и ей должен быть присвоен новый идентификатор." />
    <string id="GDkjThJcH6" text="ButterLib загружен посе официальных модулей! ButterLib должен загружаться до официальных модулей!" />
  </strings>
</base>
